"""empty message

Revision ID: 07f426ed2fe8
Revises: 
Create Date: 2021-04-07 22:56:02.040006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f426ed2fe8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.String(length=250), nullable=False),
    sa.Column('discountPercent', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updateTimeStamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voucher_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driverId', sa.String(length=250), nullable=False),
    sa.Column('driverPhoneNumber', sa.String(length=250), nullable=False),
    sa.Column('pin', sa.String(length=250), nullable=False),
    sa.Column('amountBought', sa.Integer(), nullable=False),
    sa.Column('voucherWorth', sa.Integer(), nullable=False),
    sa.Column('discountAmount', sa.Integer(), nullable=True),
    sa.Column('amountSold', sa.Integer(), nullable=True),
    sa.Column('userId', sa.String(length=250), nullable=True),
    sa.Column('userPhoneNumber', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('dateGenerated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('timeUsed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher_model')
    op.drop_table('discount_model')
    # ### end Alembic commands ###
